### PR TITLE
Use pyproject toml

### LINKED ISSUE #5: Introducing CI
## Motivations

It would be great to add the CI environment to check the codebase is well maintained.

## What should be done
I know there are some options how we introduce CI in the codebase. The followings are one example. I'm open any suggestions.
- [x] Use `pyproject.toml` instead of `setup.py`. According to the [Python official docs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/), we can write all configurations including package configs, linter configs, type checkers, and so on. This is recommended in [PEP518](https://peps.python.org/pep-0518/).
- [x] Introduce linters (ruff and mypy) using pre-commit
- [ ] Add unittests using pytest
- [x] Introduce CI using GitHub Actions to run linters and unittests

### PR DESCRIPTION
**Pull request by HideakiImamura**
Partially resolve #5 

## Motivations
According to the [Python official docs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/), we can write all configurations including package configs, linter configs, type checkers, and so on in pyproject.toml. This is recommended in [PEP518](https://peps.python.org/pep-0518/).

## Description of changes
Introduce pyproject.toml instead of setup.py

### CODE REVIEW

**Review by herilalaina — COMMENTED** [review]
Looks good to me. I believe ``setup.py`` is not needed anymore?

**Comment by HideakiImamura** [comment]
Sounds very good. I will remove the `setup.py`.

**Comment by HideakiImamura** [comment]
@herilalaina I removed setup.py. Please take a look.

**Comment by herilalaina** [comment]
Thanks @HideakiImamura  :)

**Pull request merged**
